
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: trainer
  labels:
    module: trainer
spec:
  replicas: 3
  serviceName: trainer
  selector:
    matchLabels:
      module: trainer
  template:
    metadata:
      labels:
        module: trainer
    spec:
      containers:
        - name: www
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: trainer
              mountPath: /usr/share/nginx/html
              readOnly: true
        - name: trainer
          image: docker.io/stephanzlatarev/norman-trainer
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
          volumeMounts:
            - name: trainer
              mountPath: /data
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: trainer
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: default

---
