
---

kind: Service
apiVersion: v1
metadata:
  name: trainer
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: trainer-0
  ports:
    - port: 80
      targetPort: 80

---
