on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install --omit=dev

      - name: Add bot descriptors
        run: |
          mv ${GITHUB_WORKSPACE}/norman.js ${GITHUB_WORKSPACE}/nida.js
          echo '{ "Bots": { "nida": { "Race": "Protoss", "Type": "NodeJS", "RootPath": "./", "FileName": "nida.js", "Debug": true } } }' > ${GITHUB_WORKSPACE}/LadderBots.json
          echo '{ "body": [ { "label": "StarCraft II", "code": "body/starcraft/game-ladder" } ] }' > ${GITHUB_WORKSPACE}/norman.env

      - name: Create bot zip
        run: |
          pwd
          rm -rf ${GITHUB_WORKSPACE}/nida.zip
          zip -r ${GITHUB_WORKSPACE}/nida.zip . -x '.git/*' '.github/*'
          ls -l ${GITHUB_WORKSPACE}

      - name: Upload to AI Arena
        env:
          API_TOKEN: ${{ secrets.AI_ARENA_API_TOKEN }}
        run: |
          curl -X PATCH -H "Authorization: Token ${API_TOKEN}" -F "bot_zip=@${GITHUB_WORKSPACE}/nida.zip" https://aiarena.net/api/bots/605/
